### ISSUE TITLE
Make contributing new azure resource types simplier / self contained.

### ISSUE THREAD

**Issue by erichexter** [Microsoft/AzureBot#109]
I wanted to start up a conversation about making the codebase friendlier to implementing new azure resources. Right now it looks like there are some files that require all of the resources to be included, for example the Luis Model has all the resources included in a single json file (https://github.com/Microsoft/AzureBot/blob/master/AzureBot/LuisModel/AzureBot.json) which will make contributing new resources challenging.  Other class types are organized by how the bot uses the objects so as a result, adding a new azure resource to the bot means sprinkling new classes through out the codebase.  I wanted to see if the team is open to some refactoring that would make it easier to add new resources, or at least make it easier to support a fork that includes new resources in case the team does not want to accept a pull request.

**Comment by dtzar** [comment]
We already have plans to make this cleaner to implement new Azure resource providers. @nzthiago is currently working on this with this branch https://github.com/nzthiago/azurebot/tree/nzthiago/addextensibility
Each resource provider will have its own .csproj and LUIS models with dialogues passed down from the root LUIS model.

**Comment by erichexter** [comment]
Great to hear. I am very interested in contributing. At least to the resources that we are using as part of our daily devops activity.

**Comment by nzthiago** [comment]
Thanks @erichexter, great to see you also thought of the scenario of making it easier to add more services and have multiple LUIS models. 
As @dtzar mentioned I started the work on that branch; Would be very happy to have your help, we can add you as contributor or just send PRs.
I've just pushed [the latest changes](https://github.com/nzthiago/AzureBot/commit/7ccb39c640df80ac5a577e8b4d1bf0117c2be3a3) to that branch, basically splitting the current big model into four (the four json files are in the code there too), let me know if you can get it going on your own dev environment. 
I'm also looking at the internal bot framework IScorable interface and how it might help with the back and forth between the dialogs, but none of that is in the code yet

**Comment by nzthiago** [comment]
Note: have added a new branch to the main repo with the code and removed my fork:
https://github.com/Microsoft/AzureBot/tree/addextensibility

**Comment by dtzar** [comment]
What scenarios are left to get working or what scenarios are working from the existing functionality with this branch currently?

**Comment by nzthiago** [comment]
I haven't tested forms or the long running commands. And from the root dialog to decide which of the others to go to is not being made by LUIS but instead [there's a couple of temp if / else statements looking for key words](https://github.com/Microsoft/AzureBot/blob/addextensibility/AzureBot/Dialogs/RootDialog.cs#L231-L235). Need to make this a little cleaner, and maybe the Scorable interface can help

**Comment by erichexter** [comment]
Re: the nested ifs, you could make an interface that each resource must
implement that we could scan , find all implementations of and then loop
over and look for the resource name and the associated dialogs

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by nzthiago** [comment]
Yes indeed, the current if/else was just to test that the back and forth between the dialogs worked before we got any further. 
Are you interested/available to implement the change you're recommending?

**Comment by erichexter** [comment]
yes, I make a pull request so that you can see what this looks like
concretely and then you can decide if you like the approach.​

**Comment by nzthiago** [comment]
Awesome, thanks @erichexter! Look forward to it

**Comment by erichexter** [comment]
I made the[ minimal changes I](https://github.com/erichexter/AzureBot/blob/addextensibility/AzureBot/Dialogs/RootDialog.cs#L233-L235) could to demonstrate how this would work.

Here is the [commit](https://github.com/erichexter/AzureBot/commit/344f64e94fe76f4b445bdda9d7412220e22e6555) 

I added a new project Azurebot.Types so that I could break the dependency from Azurebot to each of the implementations.

Each resource then needs to implement the interface
```Csharp

    public interface IResourceDialog
    {
        bool CanHandle(string query);
        IDialog<string> Create();
    }

```
I am by not means attached to this implementation, but this demonstrates how we can isolate the resources in a way that supports the Open Close Principal. Let me know what you think . I have not tested any of this yet. but I wanted to stub out the structure of the classes first.

**Comment by nzthiago** [comment]
@erichexter cool, looks like a great start! Please do a pull request, this branch isn't hooked up to CI/CD yet, it's still in experimental phase :).  In the DetermineResourceAsync we'll just add a check in case the dialog comes back null from the factory and then send to the Help context instead of forwarding, seems like an ok way to go about it if none of the dialogs can handle it.

**Comment by erichexter** [comment]
Hay sounds great and please know I am totally open to feedback on the code.
The class names I picked stink but I wanted to just get the basic factory
structure in place. That way we have something concert to consider. So yes
anything you want to change is totally cool with me, I will not be offended
I promise that.

The help dialog seems so obvious now that you said it. I could also imagine
in the future we could enumerate all of the available resources and their
help text



-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by nzthiago** [comment]
Great! Do send through the Pull Request when you're ready

**Comment by erichexter** [comment]
What can I do to help next? Manually test out the branch to make sure it works? Write unit tests?  something else?

**Comment by nzthiago** [comment]
Cool - yes, getting your dev environment set up so you can try it locally would be the first step. You'd have 4 different Luis applications (create them in luis.ai by instead of creating from scratch import the json files in the [LuisModel folder] (https://github.com/Microsoft/AzureBot/tree/addextensibility/AzureBot/LuisModel). Then in each of the Dialog files update the luis attributes at the top to reflect your 4 luis applications.
There's some more set up steps [here] (https://github.com/Microsoft/AzureBot/blob/gh-pages/docs/DeveloperSetup.md).

Once you have it going, a great next step for us would be to add support for another part of Azure. The Resource Group one that we have started could do with a few more, then there's Azure SQL Db, Azure Web Apps, etc, let us know if there's any you'd be comfortable with.

**Comment by nzthiago** [comment]
@erichexter will close this bug now that we have added your contribution to the extensibility branch.
