### ISSUE TITLE
can't verify my account

### ISSUE THREAD

**Issue by thdotnet** [Microsoft/AzureBot#119]
I`m trying to setup Azure Bot on my subscription, but it is stucked into the login page:

AzureBot [wsfed enabled]

For added security, we need to further verify your account 
How do you want us to verify your account? 

I`ve select my account and it keeps displaying a loading, but it's not redirecting to the portal. I've tried with most of the browsers, same problem in all of them. (chrome, edge, firefox)

Any clues?

**Comment by thdotnet** [comment]
After inspecting the console: aad.login.min.js:21 Uncaught TypeError: Cannot read property 'Result' of undefined(…)

**Comment by nzthiago** [comment]
When you say you are trying to setup Azure Bot on your subscription, do you mean you are trying to run a version of the Azure Bot yourself? [These](https://github.com/Microsoft/AzureBot/blob/gh-pages/docs/CreateAzureADforAzureBot.md) are the notes we had for you to create your Azure AD for it, and then the rest of the Developer Set Up is [here](https://github.com/Microsoft/AzureBot/blob/gh-pages/docs/DeveloperSetup.md).

If you are just trying to use the bot but it's failing, what type of user are you logging in as? A Microsoft account (hotmail.com, outlook.com, etc) or an Azure Active Directory account?

**Comment by thdotnet** [comment]
My bad, but definitely the official website is quite confusing. I could not found this link to setup the Azure AD. It just point me to this website: https://bots.botframework.com/bot?id=azurebot and has a link to this https://microsoft.github.io/AzureBot/ 

Nothing related to setup the Azure AD

**Comment by nzthiago** [comment]
No problem. In that https://microsoft.github.io/AzureBot/ page we have a phrase saying 'If you're a developer and would like to contribute or use the code, please start here.' which takes you to the Developer Set Up and then to the AD Set Up as part of it. We'll see how we can make that easier to navigate

**Comment by thdotnet** [comment]
awesome! So far this https://github.com/Microsoft/AzureBot/issues/ are the issues that MS is working on? Is there a list of the wish list? I would like to contribute for this project...

**Comment by nzthiago** [comment]
Yes, we take pull requests if you want to contribute, thanks! The latest work is in the [addextensibility branch](https://github.com/Microsoft/AzureBot/tree/addextensibility) so that's the place to look. This is a sample, just meant to show people how to get started creating a bot though, so we might not maintain it for too long.
