### ISSUE TITLE
Microsoft Teams authentication problem

### ISSUE THREAD

**Issue by dtzar** [Microsoft/AzureBot#125]
After login when using Microsoft Teams - when you copy/paste the authentication number to AzureBot, you get: "I’m sorry, but I couldn’t validate your number. Please try Authentication once again.”.
This is due to a bug in Microsoft Teams which will be resolved in the future.  

Workaround: actually type the authentication code to AzureBot

**Comment by nzthiago** [comment]
Pasting into Microsoft Teams seems to now be working
