### ISSUE TITLE
Stop VM still incurs compute charges

### ISSUE THREAD

**Issue by dtzar** [Microsoft/AzureBot#13]
When you stop a VM, it will STOP the VM but not stop the VM from incurring compute charges.

**Comment by timmyreilly** [comment]
@dtzar what's the word on this? Were you able to get it to fully shut down from the bot?

**Comment by timmyreilly** [comment]
Ahh figured it out. You want to run deallocate. 
`> az vm deallocate -g myTempResourceGroup -n MyTempVM`
