### ISSUE TITLE
Can't login with AAD

### ISSUE THREAD

**Issue by sgiovinetti** [Microsoft/AzureBot#130]
Hello,
after inserting my AAD user I receive the following error:

AADSTS90093: Does not have access to consent.

**Comment by israels** [comment]
You should try logging in with a user which is in the same tenant directory as where you register the AAD app.

**Comment by sgiovinetti** [comment]
The user is in the same tenant.

The repro is the following: from within skype I type login.

The bot asks to authenticate via oauth2  using this link:

https://login.microsoftonline.com/<mytenantID>/oauth2/authorize?resource=https:%2F%2Fmanagement.core.windows.net%2F&client_id=d6da8ea6-75cc-498b-b829-xxxxxxxxx&response_type=code&haschrome=1&redirect_uri=https:%2F%2F<mysite>.azurewebsites.com%2Fapi%2FOAuthCallback&x-client-SKU=PCL.Desktop&x-client-Ver=3.13.7.964&x-client-CPU=x64&x-client-OS=Microsoft+Windows+NT+6.2.9200.0&state=H4sIAAAAAAAEAK.....

I type the login of my company AAD account that is the same tenant where I created the app and after tabbing out before inserting the pwd my company login page appears for few milliseconds and I'm redirected immediately back to the MS login page with the error:

Sorry, but we’re having trouble signing you in. 
We received a bad request.
Additional technical information: 
Correlation ID: 126fac44-583e-4383-b786-xxxxxx 
Timestamp: 2017-02-24 07:57:37Z 
AADSTS90093: Does not have access to consent. 

I guess maybe is due to [this](https://blogs.msdn.microsoft.com/exchangedev/2014/06/05/managing-user-consent-for-applications-using-office-365-apis/) , but I'm not sure.

Moreover I would like to know if there is a workaround (maybe changing the bot code a little bit) for avoiding the login process and login directly with the app service principal maintaining a good level of security.

In fact if I use with powershell the command:
Add-AzureRmAccount -Credential $mybotappcreds -ServicePrincipal -TenantId $mytenant

I'm able to login correctly using the bot app service principal

Any advise is appreciated.

Thanks.

**Comment by israels** [comment]
It looks like might be missing the tenant component of the Oauth2 endpoint.  It takes the form of https://login.microsoftonline.com/{tenant}/oauth2/authorize
where {tenant} is either the tenant id where the app is registered for "common"

Try setting the ActiveDirectory.Tenant value in the web.config.  I'm using common and it's working fine for me.

**Comment by sgiovinetti** [comment]
I'm afraid the tenant is present, I just did not insert it in the previous link for security reasons.

The link looks like:
https://login.microsoftonline.com/abb18969xxxxxxxx/oauth2/authorize?resource=https:%2F%2Fmanagement.core.windows.net%2F&client_id=d6daxxxxxxxxx&response_type=code&haschrome=1&redirect_uri=https:%2F%2Fxxxx.azurewebsites.com%2Fapi%2FOAuthCallback&x-client-SKU=PCL.Desktop&x-client-Ver=3.13.7.964&x-client-CPU=x64&x-client-OS=Microsoft+Windows+NT+6.2.9200.0&state=H4sIxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Any other advise?

**Comment by israels** [comment]
All I can suggest is making sure to follow the [AAD instructions](https://github.com/Microsoft/AzureBot/blob/gh-pages/docs/CreateAzureADforAzureBot.md) as well as [Developer setup guide](https://github.com/Microsoft/AzureBot/blob/gh-pages/docs/DeveloperSetup.md), as well as using In private browser sessions to ensure you're not reusing any previously authenticated cookies.

I went through this and was able to host this code and login just fine.

**Comment by dtzar** [comment]
This is working for us and @israels.  The consent is likely that you do not have proper permissions with your AAD tenant to be allowed to accept this application access.  Please see steps 3 & 4 of the AAD instructions referenced by israels above and see if you can apply them to the AAD you are trying to run the bot against. 
 If this doesn't fix your issue, then comment again on this post.
