### ISSUE TITLE
AzureBot Outage

### ISSUE THREAD

**Issue by dtzar** [Microsoft/AzureBot#133]
The bot on all channels currently says: "Sorry, my bot code is having an issue."  This is due to us needing to now purchase a LUIS API key through the Azure portal, but we are currently unable due to what appears to be a bug in the portal as we are co-admins of the subscription to purchase.
![image](https://cloud.githubusercontent.com/assets/3578906/23826602/19dad688-0654-11e7-9758-cefbba41d189.png)

**Comment by nzthiago** [comment]
We needed an API key to go over the limit that the programmatic API key gives us. We have created new Endpoint Key via the Azure Portal and reconfigured the LUIS apps used by the bot with them and now the bot is working again. See: https://www.microsoft.com/cognitive-services/en-us/LUIS-api/documentation/Manage-Keys
