### ISSUE TITLE
Login takes me to a page that says I've successfully logged out

### ISSUE THREAD

**Issue by szul** [Microsoft/AzureBot#136]
When I get the login card that says authentication is required, I click the button, and it takes me a login page. I login with my Microsoft account, and then it redirects me to a page that says:

"You have been signed out. You can now close this window."

This occurs on all devices I have.

**Comment by dtzar** [comment]
Microsoft Accounts are not supported, only AAD ones. https://github.com/Microsoft/AzureBot/issues/108

**Comment by szul** [comment]
Didn't see this at first. Thanks.
