### ISSUE TITLE
Link in DeveloperSetUp-Readme is not working: 404

### ISSUE THREAD

**Issue by swildermann** [Microsoft/AzureBot#138]
Hey, the following link in the first chapter (LUIS Model) of the DeveloperSetUp is not working AzureBot-Json File (target: https://github.com/Microsoft/AzureBot/blob/gh-pages/AzureBot/LuisModel/AzureBot.json). 

A fix is appreciated.

**Comment by dtzar** [comment]
This is the model we use, but you will need to switch out the ids/secrets to work with your own LUIS subscription.  If you're doing this - can you be more specific on your problem?

**Comment by swildermann** [comment]
Just wanted to mention that the link is broken. If you don't see an issue here, neither do I.

**Comment by dtzar** [comment]
AH, gotcha sorry.  @nzthiago Either I'm missing it or it looks like this file is missing from the master repo (the current one points to gh-pages branch which definitely will fail).

**Comment by nzthiago** [comment]
Ah yes. The Luis model files are here:
https://github.com/Microsoft/AzureBot/tree/master/AzureBot/LuisModel

I've updated the page to point to that.

**Comment by swildermann** [comment]
looks fine now
