### ISSUE TITLE
no response in Microsoft Teams

### ISSUE THREAD

**Issue by swildermann** [Microsoft/AzureBot#140]
I just tried to use the AzureBot in MS Teams. But it does simply not reply at all. 
Would love to use it..

![snipimage](https://cloud.githubusercontent.com/assets/2650071/25388147/4373b28e-29cd-11e7-9c54-ac4b96f169ab.JPG)

**Comment by dtzar** [comment]
Just checked - the AzureBot is responding for me in Teams.  Can you try to remove and add the bot again?

**Comment by swildermann** [comment]
Unfortunately I do not have any option to remove the bot from the account. Any advice here?

**Comment by swildermann** [comment]
issue is not occurring anymore for me. As nobody else seems to have this issue, I am closing it now.
