### ISSUE TITLE
Cannot login from Skype

### ISSUE THREAD

**Issue by Andvell** [Microsoft/AzureBot#141]
Attempt to login, after authentication always redirects to a empty page with only the following message:
You have been signed out. You can now close this window.

**Comment by dtzar** [comment]
Did you try to login using a MSA account?  We only support AAD accounts.

**Comment by dtzar** [comment]
I'm going to assume it was a MSA account, but please comment with more detailed error messages if you are using an AAD account.

**Comment by Andvell** [comment]
Thank you. It would be nice to have MSA accounts supported though.

**Comment by dtzar** [comment]
Agreed.  It is frequent ask and people thinking there is a problem with the bot.  Please see: 
 https://github.com/Microsoft/AzureBot/issues/108
