### ISSUE TITLE
Cannot login from Slack

### ISSUE THREAD

**Issue by jdar** [Microsoft/AzureBot#142]
added AzureBot to 'tulip-global' channel.
In direct conversation with @azurebot I typed "foo"

AzureBot APP [10:46 PM] 
Please click to sign in:
----------------
Authentication Required

Upon clicking on "Authentication Required" i received:
"You have been signed out. You can now close this window."

Attempted with both Chrome and Safari. (both up-to-date)

**Comment by Pothulapati** [comment]
I had the same error from Skype and there is also an issue #141 on it.

A quick look into the URL shows the reason for the error.

>a+User+account+%27_username_%40outlook.com%27+from+identity+provider+%27live.com%27+does+not+exist+in+tenant+%27Microsoft%27+and+cannot+access+the+application+%27456443132-9b52-485d-90ed-49f37efd1c2b%27+in+that+tenant.++The+account+needs+to+be+added+as+an+external+user+in+the+tenant+first.++Sign+out+and+sign+in+again+with+a+different+Azure+Active+Directory+user+account.

Any Idea about the error? 
Is it the same for everyone?

**Comment by dtzar** [comment]
This is due to you using an @outlook.com (MSA) account.  This is unsupported.

**Comment by Pothulapati** [comment]
@dtzar Why is @outlook.com account not supported?

If it is possible to support @outlook.com , I wouldn't mind to work on that and submit a PR.

**Comment by dtzar** [comment]
We utilize the AuthBot which would be the place to do a PR, but it is a hard (if not an impossible thing to do, but things may have changed).  You can check out #108 for more information.
