### ISSUE TITLE
Skype: Overwrite the description with Description/Card

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/AzureBot#144]
Hi All,
The opening line when a user opens the Skype web control comes from the description that is set in the  settings (i.e. https://dev.botframework.com/bots/settings?id=ABC)

I want to override that in the code.
Take the Mokasha example.   We need the below message to be a desciption and a Rich form the user will fill out to kick off the chat.   We don't want the user to ask the question first then have to fill out a form. 

Is that possible?

![image](https://user-images.githubusercontent.com/4327773/26957941-a08659e4-4c8d-11e7-9c41-1d15517a909e.png)

**Comment by dtzar** [comment]
sorry @jrmcdona this has nothing to do with AzureBot.  A more appropriate location would be https://docs.microsoft.com/en-us/bot-framework/resources-support 
or
https://gitter.im/Microsoft/BotBuilder
