### ISSUE TITLE
I am not able to use Azure bot with my account error returned by bot  Oops! Something went wrong :(. Technical Details: Operation returned an invalid status code 'RequestEntityTooLarge

### ISSUE THREAD

**Issue by csukhija** [Microsoft/AzureBot#145]
When running Azure Bot I cannot select my subscription ID , the bot returns error 

I am not able to use Azure bot with my account

error returned by bot 
Oops! Something went wrong :(. Technical Details: Operation returned an invalid status code 'RequestEntityTooLarge

is there a workaround ?

**Comment by dtzar** [comment]
Are you using a MSA/Microsoft account (i.e. @outlook.com @hotmail.com etc)?  If so this is not supported.

**Comment by csukhija** [comment]
Thanks David , is there any workaround ?

**Comment by dtzar** [comment]
No sorry, please see #108

**Comment by csukhija** [comment]
Hi David,

I got it now ,
It's not related to MSA. as another member in my team is able to access.
Reason is I have more than 500 subscription ids in my account so the
request is timing out. Can I directly default or switch subscription ID ?

Thanks for your reply
