### ISSUE TITLE
Webchat bot not complying

### ISSUE THREAD

**Issue by brandon1780** [Microsoft/AzureBot#148]
@brandon1780

**Comment by brandon1780** [comment]
@brandon1780

**Comment by dtzar** [comment]
Can you please be more specific on the error you're getting?  We really can't do anything with this limited information.

**Comment by brandon1780** [comment]
AzureBot/AzureBot/Controllers/MessagesController.cs

**Comment by ChristianMontoya** [comment]
I'm facing the same issue. I originally installed AzureBot in October, hooked it up to my "work or school account" and it worked great! However, I hadn't touched it until this week. When I try typing in commands, I'm not getting any response. I know that I changed my password a week ago...is it possible that the Bot no longer has access (or delegated access?) for my work or school account?

**Comment by dtzar** [comment]
We took the bot offline.  Please see the readme at the root of the repo.

**Comment by ChristianMontoya** [comment]
Is it going to also be removed from the Teams app/bot store?

**Comment by dtzar** [comment]
Do you still see it listed there?  If so, can you please point me to a link and I will take it down.

**Comment by ChristianMontoya** [comment]
![teamsscreenshot](https://user-images.githubusercontent.com/20466676/35758643-f02a9c5a-0829-11e8-93a3-ebe04cd81de2.PNG)

**Comment by ChristianMontoya** [comment]
Unfortunately, I'm not sure how to upload to the Teams Apps/Bots store, but I see it here, with the latest version of the Windows desktop Teams App
