### ISSUE TITLE
Unable to handle not completed Runbooks

### ISSUE THREAD

**Issue by dtzar** [Microsoft/AzureBot#21]
If the runbook goes into any other status than completed, the bot will not return the status. The bot should be able to handle all statuses including starting, suspended, etc.

**Comment by ejadib** [comment]
We are explicitly filtering status for Runbooks to avoid being too verbose in the Bot. Currently we only show a message if the status is 'Running', 'Completed', or 'Failed'. Let me know if you want to show all statuses or include specific ones.

**Comment by dtzar** [comment]
Suspended is a status which is effectively failed and needs to be included.

**Comment by dtzar** [comment]
Just tested and suspended and completed are still not working for me showing the status.

**Comment by dtzar** [comment]
Verifed fixed.
