### ISSUE TITLE
Copyright?

### ISSUE THREAD

**Issue by jeffwilcox** [Microsoft/AzureBot#78]
Hi,
The `LICENSE` file for this project shows that it is copyright David Tesar.

Could someone take a look to confirm that that is correct - if this is a new Microsoft open source project it should follow the guidance given from the open source approval tool for copyright, etc.

**Comment by dtzar** [comment]
Whoops, yes it should follow MSFT guidelines. Thanks for the catch - will get fixed asap.

**Comment by dtzar** [comment]
Resolved. https://github.com/Microsoft/AzureBot/blob/master/LICENSE

**Comment by jeffwilcox** [comment]
Thanks!
